### ISSUE TITLE
关于空白页组件

### ISSUE THREAD

**Issue by jianmu297** [LinXunFeng/LXFProtocolTool#2]
我看很多APP都是全屏空白提示页，是否是因为他们像安卓一样自定义了navtitlebar作为页面布局，或者有其他解决方案？

**Comment by LinXunFeng** [comment]
@jianmu297 安卓的我不了解，iOS的空白页基本上都是只针对scrollView而已，要想导航栏也变成空白的话，可以监听空白页的一些回调来修改导航栏的背景，从而达到相同效果
