### ISSUE TITLE
EmptyDataSetable 会影响直接使用 DZNEmptyDataSet的协议和代理方法

### ISSUE THREAD

**Issue by CivelXu** [LinXunFeng/LXFProtocolTool#3]

**Comment by LinXunFeng** [comment]
是的，遵守EmptyDataSetable的Object会遵守DZNEmptyDataSet的协议和代理方法，不过遵守了EmptyDataSetable之后不是应该交由EmptyDataSetable去管理了吗？为什么还要自己去遵守和实现DZNEmptyDataSet的协议和代理方法？

**Comment by CivelXu** [comment]
@LinXunFeng 项目迁移使用 报了很多错误
