### ISSUE TITLE
Refreshable 的循环引用问题

### ISSUE THREAD

**Issue by minniexcode** [LinXunFeng/LXFProtocolTool#5]
Refreshable 的协议extension方法里面

直接使用了 self.base.initRefreshHeader 或者其他初始化 mj_header 的方法会导致循环引用

我看内存结构确实是block持有了self导致viewModel无法释放

所以viewModel 只要订阅了 refresh方法创建的Observable 必然会导致循环引用

**Comment by minniexcode** [comment]
let table_subject = rx.refresh(viewModel, tableView)
            .map { (type) -> Bool in
                return type == .header ? true: false
        }
        
        table_subject.bind(to: viewModel.refreshSubject, viewModel.loadDataSubject).disposed(by: rx.disposeBag)

**Comment by minniexcode** [comment]
let requestPage = loadDataSubject.flatMap { [weak self] (bb) -> Observable<[RefreshableModel]> in
            guard let self = self else { return Observable.empty() }
            return self.fetchList(bb)
        }
        
        let values = refreshSubject.filter({ $0 }).flatMap { [weak self] (_) -> Observable<[RefreshableModel]> in
            guard let self = self else { return Observable.empty() }
            return self.loadDataSubject
                    .withLatestFrom(requestPage)
                    .scan([], accumulator: { $0 + $1 })
        }
        
        values.bind(to: dataSources).disposed(by: rx.disposeBag)

**Comment by minniexcode** [comment]
第二个是viewMode里面的代码

**Comment by minniexcode** [comment]
![image](https://user-images.githubusercontent.com/25931089/91246154-c0394e80-e781-11ea-955c-3412813221ec.png)

**Comment by LinXunFeng** [comment]
感谢你的反馈，不过用 `Example` 测试是可以正常释放的。
我在 `2.0.1` 版本已经对其进行了弱引用，你可以更新试下。如果还有问题，欢迎提出（最好能提供 `Demo`）
