### ISSUE TITLE
使用DZNEmpty，tableViewHeader可能被挡住

### ISSUE THREAD

**Issue by yangguanghei** [LinXunFeng/LXFProtocolTool#7]

**Comment by LinXunFeng** [comment]
这个库只是对 `DZNEmptyDataSet`做了封装，没有做其它操作，你可以先看看直接使用 `DZNEmptyDataSet` 是不是也有这个问题

**Comment by yangguanghei** [comment]
> 这个库只是对 `DZNEmptyDataSet`做了封装，没有做其它操作，你可以先看看直接使用 `DZNEmptyDataSet` 是不是也有这个问题

确实会，因为它的空占位图是reload后添加到table上的，在设置tableViewHeader之后。不过感觉你这种中间多一层的方式挺好，使用起来简单了感觉简单了许多

**Comment by LinXunFeng** [comment]
感谢你的支持😀
