### ISSUE TITLE
swift中使用闭包可以不用判空了

### ISSUE THREAD

**Issue by yangguanghei** [LinXunFeng/LXFProtocolTool#8]
public func emptyDataSet(_ scrollView: UIScrollView, didTap view: UIView) {
//        if scrollView.emptyViewTapBlock != nil {
//            scrollView.emptyViewTapBlock!(view)
//        }
        scrollView.emptyViewTapBlock?(view)
    }

**Comment by LinXunFeng** [comment]
是的，这是很久之前写的代码，不影响功能所以没改
